// Central database of AI tools for creators
// To add a new tool, just add an object to this array.
// The site will automatically generate a new review page for it.

export const AI_TOOLS = [
  {
    slug: "jasper",
    name: "Jasper AI",
    tagline: "AI Writing for Marketing Teams",
    logo: "J",
    priceRange: "$49-69/mo",
    freeTier: "7-day trial",
    bestFor: "Marketing teams, brand consistency",
    pros: "Brand voice training, long-form editor, team collaboration, automation agents",
    cons: "Requires fact-checking for technical topics, Creator plan is limited",
    commission: "30% recurring for 12 months",
    cookie: "90 days",
    difficulty: "Medium",
    affiliateLink: "https://jasper.ai?aff=YOUR_ID",
    officialLink: "https://www.jasper.ai",
    reviewStatus: "live",
    longFormContent: "Jasper sits at the top for marketing teams producing at volume... [full review text here]"
  },
  {
    slug: "copyai",
    name: "Copy.ai",
    tagline: "Multi-Channel Content Automation",
    logo: "C",
    priceRange: "Free / $29-249/mo",
    freeTier: "Yes (usable free plan)",
    bestFor: "Solopreneurs, multi-channel output",
    pros: "Best free tier, workflow automation, multiple AI model options",
    cons: "Long-form content is shallow, big pricing gap between tiers",
    commission: "45% recurring (one-time model)",
    cookie: "30 days",
    difficulty: "Easy",
    affiliateLink: "https://copy.ai?via=YOUR_ID",
    officialLink: "https://www.copy.ai",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "SEO Content with Real-Time Web Access",
    logo: "W",
    priceRange: "Free / $49-79/mo",
    freeTier: "Yes (limited)",
    bestFor: "Small businesses targeting search traffic",
    pros: "Real-time web data, built-in SEO optimization, all-in-one platform",
    cons: "Writing quality is functional not inspired, platform complexity has grown",
    commission: "30% recurring (lifetime)",
    cookie: "30 days",
    difficulty: "Medium",
    affiliateLink: "https://writesonic.com?via=YOUR_ID",
    officialLink: "https://writesonic.com",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  },
  {
    slug: "rytr",
    name: "Rytr",
    tagline: "Budget-Friendly AI Writing",
    logo: "R",
    priceRange: "Free / $9/mo",
    freeTier: "Yes (10k chars/mo)",
    bestFor: "Solo creators on a budget",
    pros: "Extremely affordable, 20+ tone settings, short-form focus",
    cons: "Long-form content is thin, needs more editing than premium options",
    commission: "30% recurring",
    cookie: "60 days",
    difficulty: "Easy",
    affiliateLink: "https://rytr.me?via=YOUR_ID",
    officialLink: "https://rytr.me",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  },
  {
    slug: "surfer",
    name: "Surfer SEO",
    tagline: "Data-Driven Content Optimization",
    logo: "S",
    priceRange: "$89-199/mo",
    freeTier: "No",
    bestFor: "SEO agencies, niche site builders",
    pros: "Highest ranking long-form content, removes SEO guesswork, prevents factual errors",
    cons: "Expensive per article, dry writing style without human editing",
    commission: "25% recurring (lifetime)",
    cookie: "60 days",
    difficulty: "Hard",
    affiliateLink: "https://surferseo.com?aff=YOUR_ID",
    officialLink: "https://surferseo.com",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  },
  {
    slug: "pictory",
    name: "Pictory AI",
    tagline: "Text-to-Video for Content Repurposing",
    logo: "P",
    priceRange: "$19-99/mo",
    freeTier: "Yes (3 videos)",
    bestFor: "Video creators, content repurposing",
    pros: "Turn blog posts into videos, no technical skills required, 50% commission at top tier",
    cons: "Lower base commission (20%), higher payout threshold ($100)",
    commission: "Up to 50% recurring (lifetime)",
    cookie: "9,999 days",
    difficulty: "Easy",
    affiliateLink: "https://pictory.ai?ref=YOUR_ID",
    officialLink: "https://pictory.ai",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  },
  {
    slug: "tailwind",
    name: "Tailwind",
    tagline: "AI Social Media & Email Marketing",
    logo: "T",
    priceRange: "$19-39/mo",
    freeTier: "Yes",
    bestFor: "Social media managers",
    pros: "Three-tiered program that grows with you, first-time bonus, beginner-friendly",
    cons: "Lower starting commission (15%), social media niche only",
    commission: "Up to 25% recurring (lifetime)",
    cookie: "90 days",
    difficulty: "Easy",
    affiliateLink: "https://tailwindapp.com?aff=YOUR_ID",
    officialLink: "https://www.tailwindapp.com",
    reviewStatus: "coming_soon",
    longFormContent: "[Ready when you are to write this review]"
  }
];

// Generate category breakdowns from the data (future-proof)
export const getToolsByStatus = (status) => AI_TOOLS.filter(tool => tool.reviewStatus === status);
export const getToolsByDifficulty = (difficulty) => AI_TOOLS.filter(tool => tool.difficulty === difficulty);